{
 "title": "Power Monitoring",
 "time": { "from": "2021-08-04T13:10:19.923Z", "to": "2021-08-04T19:10:19.923Z" },
 "panels": [
  {
   "title": "Amps",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "amp" } },
   "targets": [
    { "expr": "hass_sensor_current_a{}", "legendFormat": "{{friendly_name}}" },
    { "expr": "hass_sensor_power_a{}", "legendFormat": "{{friendly_name}}" }
   ]
  },
  {
   "title": "Watts",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    { "expr": "hass_sensor_power_w{}", "legendFormat": "{{friendly_name}}" }
   ]
  },
  {
   "title": "kwh",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    { "expr": "hass_sensor_power_kwh{}", "legendFormat": "{{friendly_name}}" }
   ]
  }
 ]
}
{
 "title": "Utility Meters",
 "time": { "from": "now-7d", "to": "now" },
 "panels": [
  {
   "title": "Electricity Consumption",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "yaxes": [
    { "format": "kwatth" }
   ],
   "targets": [
    {
     "alias": "kwh",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "utilities",
     "query": "SELECT (difference(last(\"consumption\")) )/1000 FROM \"autogen\".\"utilities\" WHERE $timeFilter AND (\"endpoint_id\" = '101436633') GROUP BY time(24h)",
     "select": [
      [
       { "params": [ "consumption" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "endpoint_id", "operator": "=", "value": "101436633" }
     ]
    }
   ]
  },
  {
   "title": "Water Consumption",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "flowcfs" } },
   "yaxes": [
    { "format": "flowcfs" }
   ],
   "targets": [
    {
     "alias": "cubic feet",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "utilities",
     "query": "SELECT difference(last(\"consumption\")) FROM \"autogen\".\"utilities\" WHERE $timeFilter AND (\"endpoint_id\" = '9250289') GROUP BY time(24h)",
     "select": [
      [
       { "params": [ "consumption" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "endpoint_id", "operator": "=", "value": "101436633" }
     ]
    }
   ]
  }
 ]
}